name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get install ninja-build -y
        sudo apt-get install xorg-dev
    - name: BuildRun
      run: ./BuildRun.sh
