name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get install ninja-build -y
        sudo apt-get install xorg-dev
        sudo apt-get install freeglut3-dev
    - name: Build
      run: ./Buildtests.sh
